AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  prototype-sam-echo

Globals:
  Function:
    Timeout: 30

Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /test/echo/{proxy+}
            Method: ANY

    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./
      Dockerfile: Dockerfile
